### ISSUE TITLE
Add License...

### ISSUE THREAD

**Issue by mscuthbert** [mk270/whitakers-words#10]
Whitaker's original license said "All parts of the WORDS system, source code and data files, are made freely available to anyone who wishes to use them, for whatever purpose." -- should add this to the README.md and perhaps choose a compatible modern license to go with this (CC0?)

Mostly this issue is just to say how excited that you're making this archival version and perhaps development can continue! thanks! Feel free to close immediately.

**Comment by mk270** [comment]
I added his licensing information to the top of every single source file. You're right that it should be in a file at the root - please PR. (We can't legally relicense as CC0 without permission from the original author's estate).

Re "archival" - it is more than that - I'm fixing the code up, hoping to add macron support
