### ISSUE TITLE
Python Clone

### ISSUE THREAD

**Issue by HenryHeffan** [mk270/whitakers-words#102]
Hi All,
Dont know how else to leave a comment. Dont know if this is helpful, but I have written a clone in python if anyone is interested.
https://github.com/HenryHeffan/PyWhitakersWords
I have also done some work connecting L&S dictionary entries to DICTLINE in order to combine L&S more complete dictionary with the fact that Whitakers Words is better at detecting inflected forms than Perseus version of L&S.
Henry

**Comment by mk270** [comment]
This is just a bug tracker, not a commenting system.

This project is just about ensuring that the Whitaker's Words code is maintained (as, e.g., compilers gradually evolve - less of a problem with Ada than C). It's not about having the most appropriate way of providing what the code does, which is indeed likely to be something written in another language, like your impressive efforts!
