### ISSUE TITLE
English_to_Latin mode does not work properly.

### ISSUE THREAD

**Issue by jiangtianli91** [mk270/whitakers-words#105]
I compiled the program on mac os. The Latin_to_English works properly, but the English_to_Latin doesn't work well. For example, if I search "enjoy" it says:

```
=>enjoy
No Match
```
However, the Notre Dame online version of Whitaker's words gives

```
utor, uti, usus sum  V  DEP     3 1  DEP   [XXXAX]  
use, make use of, enjoy; enjoy the friendship of (with ABL);

fruor, fruari, fruitus sum  V  DEP     1 1  DEP   [XXXBX]  
enjoy, profit by, delight in (w/ABL);

gusto, gustare, gustavi, gustatus  V     1 1 [XXXBX]  
taste, sip; have some experience of; enjoy;

delecto, delectare, delectavi, delectatus  V  TRANS     1 1  TRANS   [XXXBO]  
|(PASS) be delighted/glad, take pleasure; (w/INF) enjoy (being/doing);

vescor, vesci, -  V  DEP     3 1  DEP   [XXXCX]  
feed on, eat, enjoy (with ABL);

perfruor, perfrui, perfructus sum  V  DEP     3 1  DEP   [XXXCX]  
have full enjoyment of, enjoy;
*
```

**Comment by spr93** [comment]
Hi -- try the "Fix case ADJ 3 4" commit above, which should address this problem.  

While working on that, I noticed that entering "enjoy" in the program will print the "utor" entry twice.  (The Notre Dame output does not have this second issue).  The second diff stops that (and other) duplications in English output.

**Comment by jiangtianli91** [comment]
I have compiled your new commit. It works perfectly now! Thanks!
