### ISSUE TITLE
Single-character words 

### ISSUE THREAD

**Issue by spr93** [mk270/whitakers-words#120]
I'm submitting this as an issue because it's a significant issue with a simple fix, and I've already got a larger pull request pending:

Make_Words returns no output when a valid single-character word (e.g., "o"; any single-character Roman numeral) appears at the end of an input line.  This includes the situation where a single-character word is the only input.

The cause is Make_Words's loop condition, which uses a < instead of <= ("while Indices (Next_Index) < Line'Last").

Please see this diff:  https://github.com/mk270/whitakers-words/pull/104/commits/41fabacd04a3b62adfc6e77380e8755167e134c5

**Comment by mk270** [comment]
your fix has been merged; thanks!
