### ISSUE TITLE
make fails in a virtual machine in Qubes, OS is fedora 33

### ISSUE THREAD

**Issue by gitboch** [mk270/whitakers-words#121]
This is what I get, when I run "make" in the directory containing words 
[user@work words]$ make
gprbuild -p -j4 commands.gpr
gprconfig: can't find a native toolchain for language 'ada'
gprconfig: can't find a native toolchain for language 'ada'
words_engine.gpr:9:25: warning: libraries are not supported on this platform
support_utils.gpr:9:25: warning: libraries are not supported on this platform
latin_utils.gpr:8:25: warning: libraries are not supported on this platform
latin_utils.gpr:3:17: no compiler for language "Ada", cannot compile "latin_utils-config.adb"
gprbuild: *** compilation phase failed
make: *** [Makefile:40: commands] Fehler 4
In Fedora ADA is part of GCC, which is installed. gprbuild and the development package is installed.

I am absolutely new to ADA, so maybe I made an obvious mistake oder did not install a necessary dependency.

**Comment by gitboch** [comment]
OK. I did not install gcc-gnat. gcc does not install this, it has to be installed separately. After that, make did do what it should do.

**Comment by mk270** [comment]
Ah, no worries. Is there anything in the documentation which we ought to do to make this more obvious, so others do not have the same problems?

**Comment by gitboch** [comment]
Heading "Build-time Dependencies"
On Fedora 33 and 34 and probably the upcoming 35, you can install these as follows:
sudo dnf install gcc gcc-gnat gprbuild

**Comment by gitboch** [comment]
And thank you for your good work on Whitakers words! Good program and I rather needed it.
