### ISSUE TITLE
archives.nd no longer hosts Whitaker's Words content

### ISSUE THREAD

**Issue by Dakewlmancoding** [mk270/whitakers-words#122]
From what I can see, the previous host of Whitaker's Words online (https://archives.nd.edu/words.html) No longer hosts it. I have noticed the following effects from this:

-WORDS Online no longer has an English to Latin translator

-The links to download runnable copies for Windows and MacOS now link to a 404 page

Apologies if there is a misunderstanding on my end/I'm not up to speed on something. I used to use this exclusively from the Notre Dame Archives page and just became aware it was an ongoing, open source project!

**Comment by mk270** [comment]
thanks. I've updated the download links. This is a temporary fix. We'll come up with a better solution long-term in due course.

Engish to Latin will be there in a week or two
