### ISSUE TITLE
make fails on latin_utils-dictionary-package and latin_utils-inflections_package

### ISSUE THREAD

**Issue by jg110** [mk270/whitakers-words#125]
Attempting to build on Fedora 36 with gcc-gnat and gprbuild installed:

```
$ make
gprbuild -p -j4 commands.gpr
Compile
   [Ada]          makeewds.adb
   [Ada]          latin_utils-inflections_package.adb
   [Ada]          latin_utils-dictionary_package.adb
   [Ada]          support_utils-dictionary_form.adb
latin_utils-dictionary_package-parse_record_io.adb:28:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-parse_record_io.adb:30:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-parse_record_io.adb:32:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-parse_record_io.adb:44:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-parse_record_io.adb:46:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-parse_record_io.adb:48:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-noun_entry_io.adb:28:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-noun_entry_io.adb:30:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-noun_entry_io.adb:42:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-noun_entry_io.adb:44:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-pronoun_entry_io.adb:28:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-pronoun_entry_io.adb:40:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-propack_entry_io.adb:28:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-propack_entry_io.adb:40:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-adjective_entry_io.adb:28:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-adjective_entry_io.adb:39:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-numeral_entry_io.adb:32:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-numeral_entry_io.adb:34:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-numeral_entry_io.adb:46:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-numeral_entry_io.adb:48:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-verb_entry_io.adb:28:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-verb_entry_io.adb:40:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-part_entry_io.adb:51:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-part_entry_io.adb:128:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-translation_record_io.adb:30:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-translation_record_io.adb:32:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-translation_record_io.adb:34:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-translation_record_io.adb:36:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-translation_record_io.adb:48:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-translation_record_io.adb:50:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-translation_record_io.adb:52:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-translation_record_io.adb:54:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-dictionary_entry_io.adb:29:33: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-dictionary_entry_io.adb:33:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-dictionary_entry_io.adb:35:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-dictionary_entry_io.adb:48:27: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-dictionary_entry_io.adb:52:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-dictionary_entry_io.adb:54:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-decn_record_io.adb:29:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-decn_record_io.adb:41:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-tense_voice_mood_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-tense_voice_mood_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-tense_voice_mood_record_io.adb:42:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-tense_voice_mood_record_io.adb:44:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-noun_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-noun_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-noun_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-noun_record_io.adb:44:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-noun_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-noun_record_io.adb:48:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-pronoun_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-pronoun_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-pronoun_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-pronoun_record_io.adb:44:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-pronoun_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-pronoun_record_io.adb:48:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-propack_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-propack_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-propack_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-propack_record_io.adb:44:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-propack_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-propack_record_io.adb:48:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-adjective_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-adjective_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-adjective_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-adjective_record_io.adb:34:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-adjective_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-adjective_record_io.adb:48:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-adjective_record_io.adb:50:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-adjective_record_io.adb:52:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-numeral_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-numeral_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-numeral_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-numeral_record_io.adb:34:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-numeral_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-numeral_record_io.adb:47:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-numeral_record_io.adb:49:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-numeral_record_io.adb:51:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-verb_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-verb_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-verb_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-verb_record_io.adb:44:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-verb_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-verb_record_io.adb:48:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-vpar_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-vpar_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-vpar_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-vpar_record_io.adb:34:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-vpar_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-vpar_record_io.adb:48:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-vpar_record_io.adb:50:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-vpar_record_io.adb:52:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-supine_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-supine_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-supine_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-supine_record_io.adb:44:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-supine_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-supine_record_io.adb:48:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-quality_record_io.adb:44:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-quality_record_io.adb:120:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-inflection_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-inflection_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-inflection_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-inflection_record_io.adb:34:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-inflection_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-inflection_record_io.adb:48:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-inflection_record_io.adb:50:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-inflection_record_io.adb:52:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]

   compilation of latin_utils-dictionary_package.adb failed
   compilation of latin_utils-inflections_package.adb failed

gprbuild: *** compilation phase failed
make: *** [Makefile:40: commands] Error 4
```

Package versions are gprbuild 2020 and gcc-gnat 12.2.1. I'm not familiar with Ada, so I don't know if there's a way to get more useful output from the compiler. If so, let me know and I can try to get more details on why these files aren't compiling.

**Comment by spr93** [comment]
short-term fix:  try adding -wn as a gprbuild parameter.  that work?
    On Friday, August 26, 2022 at 06:44:46 PM PDT, jg110 ***@***.***> wrote:  
 
 


Attempting to build on Fedora 36 with gcc-gnat and gprbuild installed:
$ make
gprbuild -p -j4 commands.gpr
Compile
   [Ada]          makeewds.adb
   [Ada]          latin_utils-inflections_package.adb
   [Ada]          latin_utils-dictionary_package.adb
   [Ada]          support_utils-dictionary_form.adb
latin_utils-dictionary_package-parse_record_io.adb:28:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-parse_record_io.adb:30:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-parse_record_io.adb:32:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-parse_record_io.adb:44:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-parse_record_io.adb:46:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-parse_record_io.adb:48:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-noun_entry_io.adb:28:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-noun_entry_io.adb:30:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-noun_entry_io.adb:42:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-noun_entry_io.adb:44:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-pronoun_entry_io.adb:28:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-pronoun_entry_io.adb:40:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-propack_entry_io.adb:28:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-propack_entry_io.adb:40:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-adjective_entry_io.adb:28:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-adjective_entry_io.adb:39:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-numeral_entry_io.adb:32:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-numeral_entry_io.adb:34:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-numeral_entry_io.adb:46:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-numeral_entry_io.adb:48:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-verb_entry_io.adb:28:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-verb_entry_io.adb:40:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-part_entry_io.adb:51:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-part_entry_io.adb:128:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-translation_record_io.adb:30:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-translation_record_io.adb:32:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-translation_record_io.adb:34:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-translation_record_io.adb:36:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-translation_record_io.adb:48:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-translation_record_io.adb:50:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-translation_record_io.adb:52:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-translation_record_io.adb:54:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-dictionary_entry_io.adb:29:33: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-dictionary_entry_io.adb:33:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-dictionary_entry_io.adb:35:30: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-dictionary_entry_io.adb:48:27: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-dictionary_entry_io.adb:52:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-dictionary_package-dictionary_entry_io.adb:54:24: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-decn_record_io.adb:29:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-decn_record_io.adb:41:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-tense_voice_mood_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-tense_voice_mood_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-tense_voice_mood_record_io.adb:42:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-tense_voice_mood_record_io.adb:44:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-noun_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-noun_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-noun_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-noun_record_io.adb:44:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-noun_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-noun_record_io.adb:48:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-pronoun_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-pronoun_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-pronoun_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-pronoun_record_io.adb:44:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-pronoun_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-pronoun_record_io.adb:48:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-propack_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-propack_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-propack_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-propack_record_io.adb:44:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-propack_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-propack_record_io.adb:48:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-adjective_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-adjective_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-adjective_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-adjective_record_io.adb:34:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-adjective_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-adjective_record_io.adb:48:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-adjective_record_io.adb:50:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-adjective_record_io.adb:52:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-numeral_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-numeral_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-numeral_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-numeral_record_io.adb:34:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-numeral_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-numeral_record_io.adb:47:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-numeral_record_io.adb:49:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-numeral_record_io.adb:51:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-verb_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-verb_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-verb_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-verb_record_io.adb:44:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-verb_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-verb_record_io.adb:48:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-vpar_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-vpar_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-vpar_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-vpar_record_io.adb:34:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-vpar_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-vpar_record_io.adb:48:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-vpar_record_io.adb:50:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-vpar_record_io.adb:52:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-supine_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-supine_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-supine_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-supine_record_io.adb:44:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-supine_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-supine_record_io.adb:48:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-quality_record_io.adb:44:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-quality_record_io.adb:120:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-inflection_record_io.adb:28:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-inflection_record_io.adb:30:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-inflection_record_io.adb:32:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-inflection_record_io.adb:34:18: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-inflection_record_io.adb:46:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-inflection_record_io.adb:48:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-inflection_record_io.adb:50:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]
latin_utils-inflections_package-inflection_record_io.adb:52:12: warning: pragma Unreferenced given for "Spacer" [enabled by default]

   compilation of latin_utils-dictionary_package.adb failed
   compilation of latin_utils-inflections_package.adb failed

gprbuild: *** compilation phase failed
make: *** [Makefile:40: commands] Error 4

Package versions are gprbuild 2020 and gcc-gnat 12.2.1. I'm not familiar with Ada, so I don't know if there's a way to get more useful output from the compiler. If so, let me know and I can try to get more details on why these files aren't compiling.

**Comment by jg110** [comment]
No, although the file list initially printed is slightly different. I now get

```
$ make
gprbuild -p -j4 -wn commands.gpr
Compile
   [Ada]          latin_utils-inflections_package.adb
   [Ada]          latin_utils-dictionary_package.adb
   [Ada]          support_utils-word_parameters.adb
   [Ada]          support_utils-uniques_package.ads
   [Ada]          support_utils-line_stuff.adb
   [Ada]          support_utils-developer_parameters.adb
```

followed by all of the "warning: pragma" messages and the failure to build those two adb files.

**Comment by spr93** [comment]
If I'm understanding you right, you're only seeing compiler "warnings," not "errors," which probably means there's some a gprbuild or gcc setting that's causing pragma warnings to be treated as errors.  I'm surprised -wn (warnings: not errors) didn't fix it, but I'm not super familiar with how gprbuild resolves conflicts between command-line arguments and non-command-line settings.
Let's see if gprbuild is the source of the issue by using gnatmake.  From the src/ directory:gnatmake -j4 -O2 -I./commands -I./latin_utils -I./support_utils -I./tools -I./words_engine words.adb -o ../bin/wordsgnatclean words


    On Friday, August 26, 2022 at 08:54:06 PM PDT, jg110 ***@***.***> wrote:  
 
 


No, although the file list initially printed is slightly different. I now get
$ make
gprbuild -p -j4 -wn commands.gpr
Compile
   [Ada]          latin_utils-inflections_package.adb
   [Ada]          latin_utils-dictionary_package.adb
   [Ada]          support_utils-word_parameters.adb
   [Ada]          support_utils-uniques_package.ads
   [Ada]          support_utils-line_stuff.adb
   [Ada]          support_utils-developer_parameters.adb

followed by all of the "warning: pragma" messages and the failure to build those two adb files.

**Comment by jg110** [comment]
```
$ gnatmake -j4 -O2 -I./commands -I./latin_utils -I./support_utils -I./tools -I./words_engine words.adb -o ../bin/wordsgnatclean words
gnatmake: cannot specify a single executable for several mains
```

Playing around with the gprbuild flags, it looks like if I set a flag in the Makefile it's basically ignored. I tried -ws (suppress all warnings) and still get all the pragma warnings when I run make.

**Comment by jg110** [comment]
Taking the `words` off of the end of the `gnatmake` command allows it to build successfully.

**Comment by mk270** [comment]
Ok - @jg110 is this a real error?

I must confess I don't fully understand all the nuances of the build system. But it's supposed to treat warnings as errors. Part of the point of maintaining the code is to fix the areas which start giving rise to new warnings in the compilers as they evolve, as over time, they add to make the thing irretrievably difficult to compile, however this happens more slowly in Ada than in C.

**Comment by jg110** [comment]
If what's stopping the build is that warnings are treated as errors, then yes, I'd say a failure to build with the expected build system command and the expected compiler flags is a real error. If you mean an actual syntax error in the Ada code, I don't think there is one.

Edit: I'll also add that the resulting binary refuses to run because it's missing a file called INFLECTS.SEC it expects to have in its directory. ~~These could probably be built manually but being able to use the Makefile normally would be more desirable.~~ I'm actually not sure if that's supposed to be an output of the build process or a renamed version of INFLECTS.LAT.

**Comment by spr93** [comment]
I spun up a Fedora 36 vm and installed that distribution's gnat-gcc (12.2.1 built 2022-08-19) and gprbuild packages.  Building does indeed fail because pragma unreferenced (spacer) in a bunch of the IO packages generate warnings, which are then are treated as errors (because of -gnatwae in shared.gpr).  
I've not seen pragma unreferenced generate warnings like that on any other gcc configuration, even with -gnatwae. 
If warnings are unstable across gnat versions or configurations--and it looks like they are--then -gnatwae may be overkill for end users.

    On Saturday, August 27, 2022 at 11:30:49 AM PDT, jg110 ***@***.***> wrote:  
 
 


If what's stopping the build is that warnings are treated as errors, then yes, I'd say a failure to build with the expected build system command and the expected compiler flags is a real error. If you mean an actual syntax error in the Ada code, I don't think there is one.

**Comment by mk270** [comment]
Thanks all for sorting this out.

It is regrettable that the compiler is now changing beneath us with such rapidity, but that is the way of things nowadays.
