### ISSUE TITLE
Discussion: let's use milestones to group features for release

### ISSUE THREAD

**Issue by Fuco1** [mk270/whitakers-words#25]
Since we are going beyond the "base" WW, we will need to do releases every once in a while.

I suggest we put _feature_ and _bug_ tasks under a milestone so we can easily review what is done and what isn't to produce reasonable changelogs.

Alternatively, tags & search works too, but I find milestones to be a better interface.

**Comment by mk270** [comment]
Github changes the interface more quickly than anyone should be expected to adapt, so I'm fairly agnostic on the question whether to use milestones or labels.

I don't plan on going beyond the base WW until it's fixed, and I don't see that happening for quite some time. 

To do a release as it would be understood by non-hackers, we need the ability to create, test and distribute binaries for several platforms, which we don't really have yet. See http://mk270.github.io/whitakers-words/plan.html for what my own priorities are; basically organisational for the time being (get people who can do the packaging, get testers, get an organisational framework, get the dataset re-usable etc)

**Comment by mk270** [comment]
Ok, I've set up a milestone.
