### ISSUE TITLE
Style and quality changes that need to be done

### ISSUE THREAD

**Issue by darkestkhan** [mk270/whitakers-words#27]
I will list all style changes that need to be done for style changes to be completed:
- ~~all names (especially public ones) shall¹ use Ada naming convention [easy but tedious]~~ ²
- ~~there shall spaces between binary operators and on left side of left parenthesis (unless it is preceded by apostrophe) [easy but tedious] ³~~
- ~~there shall be no lines longer than 80 columns~~
- all identifiers shall be as self-documenting as reasonably possible (s, ss, ssa? wtf does this even mean?) [one caveat - beside capitalization - don't change values in enumerations]

Also try to use FIXME, TODO and NOTE for (respectively) comments of bugs/problems, things that have to be done, description of non-obvious behavior, as they are easy to search for (with grep for example)

¹ used shall as 'should' is too permissive
² for interested: https://en.wikibooks.org/wiki/Ada_Style_Guide is commonly used quality and style guide for Ada, together with some examples and rationales behind style rules

**Comment by mk270** [comment]
I've fixed all 10K or so style warnings

I'm going to break this ticket up into smaller issues (the FIXME/TODO stuff is important; the variable case stuff can surely wait until we've got a release out).

**Comment by darkestkhan** [comment]
Good work. Really. I'm still working on that Inflections_Package (now mostly separating IO package bodies, making state more local, identifiers more self-documenting etc.).
Cases I'm fixing along the way - no point in going all out specifically targeting cases.

**Comment by mk270** [comment]
There's a block of massively duplicated code in Latin_Utils.Inflections_package.establish_inflections_section - it looks like a cut-n-paste of four copies of forty identical lines that differ by a single character (or something). Please factor that craziness into oblivion.

**Comment by darkestkhan** [comment]
@mk270 Chill, just found a way to factor it out nicely (a bit of a hack actually). They are not exactly 4 copies of same function - it is two copies of two functions differing by presence of one "exit when" statement. [and they further differ by character used in boolean expression inside that "exit when"]

**Comment by mk270** [comment]
Thank you, that is _excellent_ news :)
