### ISSUE TITLE
deprecate build-time dependency on gprbuild

### ISSUE THREAD

**Issue by mk270** [mk270/whitakers-words#29]
see https://gcc.gnu.org/onlinedocs/gnat_ugn/Automatically-Creating-a-List-of-Directories.html#141
https://gcc.gnu.org/onlinedocs/gnat_ugn/Using-gnatmake-in-a-Makefile.html

alternatively, establish that tdm-gcc can provide gprbuild appopriately

**Comment by darkestkhan** [comment]
But what for?
