### ISSUE TITLE
make functionality available as a library

### ISSUE THREAD

**Issue by mk270** [mk270/whitakers-words#3]

**Comment by darkestkhan** [comment]
I have identified a number of packages that are used as libraries (ie. Dictionary_Package, Inflections_Package, Parse, Strings_Package, Char_Utils) and could make them into child packages of some other package and provide gprfile for it. Question is: what would be the name of such library?
util is too generic... [an additional side bonus of doing this would be speed up of compilation]

**Comment by mk270** [comment]
do you mean i.e., or e.g.?

just call it something like latin_util

**Comment by darkestkhan** [comment]
Roger that. Actually it is a good name... (/me has terrible naming sense)

**Comment by mk270** [comment]
by the way - are you willing to distribute your changes to WORDS under the same terms as WORDS itself?

**Comment by darkestkhan** [comment]
Yes, I'm willing to do so - in fact I'm even adding the same license header in all new files I create.

**Comment by darkestkhan** [comment]
Oh boy... this is pretty invasive - library units need to be moved to separate dir (easy), new gpr file for library needs to be created (easy)... then you need to track all files and apply the changes (tedious...)
Here is basis for library - I didn't edit Makefile as my makefoo is lacking.
https://github.com/darkestkhan/whitakers-words/tree/library
Any comments about it?

**Comment by mk270** [comment]
cheers

I was worried about the Makefile getting in the way of splitting directories.

Separately, I'd organise the directories somewhat differently, but let's get the build working properly first.

**Comment by mk270** [comment]
now in branch "3-split-out-library" - I'm going to merge this unless there's some major issue

**Comment by darkestkhan** [comment]
Directories/directories names can always be changed.

**Comment by darkestkhan** [comment]
I see now how you placed directories - nice way to do it :)

**Comment by mk270** [comment]
cheers

The source code has certainly been criticised in the past for the "all in one directory" approach, and so this is a step forward on that count.

**Comment by darkestkhan** [comment]
I bet that there are still some more packages that could be moved into library, but now at least we have it :+1: 

and I meant e.g. there ... funny, I always thought that ie. is "in example" - had to look this up to clear my misunderstanding. And thanks for pointing this out.

**Comment by mk270** [comment]
"X i.e. A, B and C" implies "X == A, B and C"
"X e.g. A, B, and C" implies "A, B and C is a _proper_ subset of X"

**Comment by mk270** [comment]
Ok, there is a plan for how to do this.

The main guts of WORDS is in three files:
- parse.adb
- list_package.adb
- word_package.adb

These juggle around a statically allocated blob of data called (Pa / Pa_Last), and ultimately convert it into two arrays called Dma and Sraa, which are promptly passed through to an I/O routine. The key function is List_Package.List_Stems(). 

What we're going to do is convert List_Stems() to use Ada.Collections.Vectors for Dma and Sraa, and then allow those values to be passed up to the main Parse() / Parse_Latin_Word() routines and returned without using I/O.

**Comment by ids1024** [comment]
It will also be necessary at some point to create a c API so it can be called from other programming languages.

**Comment by mk270** [comment]
The cases I'm most concerned with are calling it from Java (for @ids1024 's own use case) and spitting out JSON. Ideally we'd be able to go from Java to Ada directly without going through C.

**Comment by darkestkhan** [comment]
@mk270 somehow I feel that going through C is better - it permits more languages to use functionality of library. In addition it happens so that Ada has defined interfacing with C. Not sure how I would go about interfacing with java.

**Comment by mk270** [comment]
@darkestkhan I was not ruling out C-calls-Ada; I was saying that I wasn't ruling out Java-calls-Ada . Obviously we want C-calls-Ada, for exactly the reason you state. That is, I want to do C-calls-Ada, _and_, if possible, Java-calls-Ada.

**Comment by darkestkhan** [comment]
I don't think you can do java-calls-ada directly - you can do binding in C and then call C from Java.

**Comment by mk270** [comment]
@darkestkhan that is very likely true; I have seen claims to the contrary, but I'm not certain.

**Comment by mk270** [comment]
I have tidied up the interaction between the routines that handle the whole input line and the individual words; they used to have complex interacting state machines and shared mutable data, which has largely been eliminated.

**Comment by mk270** [comment]
The next piece of work in this overall "library" project is #64 , on branch `prepare-for-api`

**Comment by ids1024** [comment]
Great! So, is the c api the next thing that needs to be added?

**Comment by mk270** [comment]
@ids1024 - I'm afraid not; check out http://mk270.github.io/whitakers-words/plan.html under "Medium-term plan"
