### ISSUE TITLE
makeinfl is raising Ada.IO_Exceptions.Data_Error a LOT.

### ISSUE THREAD

**Issue by darkestkhan** [mk270/whitakers-words#36]
This is visible when running makeinfl - all these ***\* lines are Put by exception handler.
(if you replace it with:

``` ada
            exception
               when E : Constraint_Error | IO_Exceptions.Data_Error  =>
                  Put_Line (Ada.Exceptions.Exception_Name (E) & " " &
                            line (1 .. last));
```

then you will have exception name printed instead of useless ***\* (you need to with Ada.Exceptions for that))

Quite unfortunately subprogram responsible for that - file_inflection_sections - is heavy user of state, which makes understanding flow of data quite hard (not to mention not so surprising issue with cryptic identifiers)

**Comment by mk270** [comment]
Ok, almost all of those errors are from not handling CRLF

**Comment by mk270** [comment]
And the other thing that causes it is utterly grotesque:

if there is more than one comment marker on a line, the next line is misinterpreted:

```
--  nullus type adjectives           (with ius in GEN and i in DAT sing)
--  nullus (gen) nullius  =>  null null zzz zzz   --  no COMP or SUPER
ADJ   1 3 NOM S M POS   1 2 us       X A
ADJ   1 3 GEN S X POS   2 3 ius      X A
ADJ   1 3 DAT S X POS   2 1 i        X A
ADJ   1 3 DAT S X POS   2 1 o        X D    --  G&L  76 29
```

The two "--" markers in the second line here cause the third line to be corrupted; the third line is read into the buffer that held the second line, giving

```
ADJ   1 3 NOM S M POS   1 2 us       X Azzz zzz
```

... and the "Azzz" fails to pattern match as a Frequency type, raising DATA_ERROR

The comments are fairly important (that G&L for instance stands for Gildersleeves & Lodge; it's basically a missing optional field).
