### ISSUE TITLE
Establish src/tools as an integrated part of the build process; adjust composition of Latin_Util library

### ISSUE THREAD

**Issue by darkestkhan** [mk270/whitakers-words#37]
I have created branch ( https://github.com/darkestkhan/whitakers-words/tree/tools ) containing gpr file for building thing tools in src/tools. Thing is: there were many warnings triggered when I tried to compile them all, and chances are high that some additional packages from src/commands need to be moved under Latin_Util library. (this is relatively simple and good)

**Comment by mk270** [comment]
Thanks - I'll take a look

**Comment by mk270** [comment]
I've tidied up tools/check.adb enough to get it to compile, but it depends on "line_stuff", which is currently in src/commands, and itself depends on various other files.

I think we may need another library dir, but I can't think of a good name right now.

**Comment by darkestkhan** [comment]
Not really. We need to put a lot of stuff under library and then slowly clean it up.
I already moved everything necessary under Latin_Utils. Will be pushing in a moment.
[also there is "misplaced then" that seems to need newer version of gcc than 4.6 - I already fixed those in check.adb, will fix any other if they ever occur]

**Comment by darkestkhan** [comment]
can't push now due to merge conflicts with latest changes :(
