### ISSUE TITLE
remove state from List_Package.List_Stems()

### ISSUE THREAD

**Issue by mk270** [mk270/whitakers-words#45]
this function should not have "in out" parameters; fixing this is at the core of making WORDS more flexible

**Comment by mk270** [comment]
The procedure itself is 934 lines long(!)

**Comment by mk270** [comment]
now <= 800 lines

**Comment by mk270** [comment]
<= 700

**Comment by mk270** [comment]
now <= 300

**Comment by mk270** [comment]
now <= 80; result!

However, it calls down into other extremely long procedures such as List_Sweep()

**Comment by mk270** [comment]
I have amended List_Sweep() such that it no longer mutates its arguments; this is a big step towards detaching the parser from I/O and wrapping it in an API.

**Comment by darkestkhan** [comment]
Congrats! Cutting down function from 900 lines to just 80 is no trivial
matter.
