### ISSUE TITLE
comma in the input in Words Online causes an error

### ISSUE THREAD

**Issue by Ansa211** [mk270/whitakers-words#73]
go to http://latin.ucant.org/
enter "Ego sum pauper, nihil habeo." or any other string containing a comma
there is an error pop-up saying "Error: Non-Latin character in word"

The same input is handled correctly in the offline version (as compiled from current master).
The full stop itself does not cause any problems - it's in the comma.

**Comment by mk270** [comment]
thanks - well spotted and well reported. Looking into it!

**Comment by mk270** [comment]
fixed
