### ISSUE TITLE
Unexpected exception in CYCLE_OVER_PA processing words with the iv SUFFIX

### ISSUE THREAD

**Issue by Ansa211** [mk270/whitakers-words#76]
I ran across over 100 words (with a total of over 1000 occurrences) words that give me the `Unexpected exception in CYCLE_OVER_PA processing ...`. 
A quick look on the list of words that emit this warning suggests that this is a group of similarly derived adjectives, and that the problem only occurs with feminine/neuter forms ending in `-a`:

`miraculosa, opprobriosa, poenosa, saporosa, taediosa, venenosa`
`prophetica`

Most of them are formed by the `-iv` SUFFIX with 85 of them ending in `-tiva`
`ablutiva, acquisitiva, adinventiva, aedificativa, aestimativa, afflictiva, appetitiva, assimilativa, augmentativa, benefactiva, calefactiva, cogitativa, cognitiva, cohibitiva, communicativa, commutativa, concretiva, confortativa, consecrativa, consiliativa, consummativa, contumeliativa, deiectiva, designativa, determinativa, distinctiva, divinativa, excitativa, executiva, factiva, figurativa, formativa, germinativa, gubernativa, impeditiva, imperativa, impetrativa, impletiva, inflativa, informativa, inquisitiva, intellectiva, interpretativa, intimativa, iudicativa, iustificativa, liquefactiva, medicativa, memorativa, mitigativa, moderativa, modificativa, negotiativa, nutritiva, operativa, opinativa, ordinativa, participativa, perceptiva, perfectiva, praeceptiva, praefigurativa, praeparativa, privativa, productiva, prohibitiva, provocativa, rarefactiva, receptiva, recordativa, reformativa, regnativa, resolutiva, respectiva, sanativa, sanctificativa, significativa, speculativa, spirativa, subiectiva, susceptiva, transitiva, unitiva, vindicativa, vivificativa`
`apprehensiva, conversiva, dimensiva, discursiva, discussiva, divisiva, laesiva, ostensiva, remissiva, successiva, visiva`

(If this helps: I am running `words` on a wordlist extracted from Summa Theologiae by Thomas Aquinas.)

**Comment by mk270** [comment]
Bloody corpus linguistics :) ... the bug is probably in Aquinas rather than Cycle_Over_Pa() ;)

This is going to be hard to fix. Thanks again for the report!

**Comment by mk270** [comment]
There is an unchecked hard limit on how many inflections can be displayed

We need to check the limit, and work out why these feminine / neuter case-ambiguous words are using up twice the expected space

**Comment by mk270** [comment]
Now apparently fully fixed, thanks to @spr93
