### ISSUE TITLE
API: disentangle parse results from output generation

### ISSUE THREAD

**Issue by mk270** [mk270/whitakers-words#82]
The context here is src/words_engine/words_engine-list_package.adb

**Comment by ids1024** [comment]
Could you explain exactly what this is about? I presume this is related to getting a data structure as the result of analysing a word and not printing to the screen, but I don't know exactly what the issue is.

**Comment by mk270** [comment]
The problem is that the results of analysing a word are mutated repeatedly in the process of displaying the analyses.

Put_Parse_Details () https://github.com/mk270/whitakers-words/blob/f31aa56ec519dcefd4f4bae96a7279d971809277/src/words_engine/words_engine-list_package.adb#L606 should be a pure function. So too should Put_Word_Meaning () https://github.com/mk270/whitakers-words/blob/f31aa56ec519dcefd4f4bae96a7279d971809277/src/words_engine/words_engine-list_package.adb#L278.

(by "pure" I mean no side-effects other than I/O; in particular, no frobbing of global state or the subprogrammes' arguments)

**Comment by mk270** [comment]
So we need to reduce the interleaving of output and mutations until it's eliminated
