### ISSUE TITLE
web version hangs on lengthy entries

### ISSUE THREAD

**Issue by air-wreck** [mk270/whitakers-words#87]
This is a bug with the linked project website; I'm not sure if there's a better place for this.

I've noticed that the [online version](https://latin.ucant.org/) seems to hang when I try to translate *canis*. After building Words from the repository and running `bin/words`, I found that *canis*, by virtue of having lots of lengthy entries, causes the interactive environment to prompt the user to press `ENTER` for more. It seems like the online version is doing something similar, causing it to hang. I haven't been able to identify any other Latin words that cause this problem.

For comparison, the [CGI version](http://archives.nd.edu/cgi-bin/wordz.pl?keyword=canis) hosted by Notre Dame seems to translate *canis* just fine.

**Comment by mk270** [comment]
is this possibly to do with malformed JSON?

**Comment by ids1024** [comment]
The behavior @air-wreck is describing in the command line version can be disabled by setting `PAUSE_IN_SCREEN_OUTPUT` to `N` in `WORD.MDV` (which can be set using the `!` command).

**Comment by mk270** [comment]
yes, but I believe @air-wreck 's conclusion may be unwarranted, and that the actual problem is caused by malformed JSON. The option in ```WORD.MDV``` is, I believe, already set to ```N```

**Comment by ids1024** [comment]
Fair enough. It looks like it is invalid json:

```bash
curl "https://latin.ucant.org/cgi-bin/translate.cgi?query=canis" | python -c 'import json, sys; print(json.load(sys.stdin))'
```

```
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 1506 (char 1525)
```

**Comment by ids1024** [comment]
It looks like the issue is that `"` (and presumably other characters) is not being escaped when generating the json.

**Comment by mk270** [comment]
fixed. replaced hand-rolled JSON generator with GNATCOLL.JSON
