### ISSUE TITLE
Build failing with recent gcc due to -gnatwe

### ISSUE THREAD

**Issue by ids1024** [mk270/whitakers-words#88]
The build fails with various `use clause for package "<some package>" has no effect` warnings, which are turned into errors.

Removing `-gnatwe` from the .gpr files allows it to compile, though obviously it still prints those warnings.

**Comment by mk270** [comment]
ok - thanks for this report; let's just remove the offending use-clauses. I've done a handful already.

**Comment by mk270** [comment]
ok I have got rid of these warnings; sadly it doesn't build with gnat-8, for (what appear to be) unrelated reasons
